import { Button } from 'antd/lib/radio'
import Head from 'next/head'
import Login from '../components/Login'
import { Row, Col } from 'antd'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by Quiz App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'block' }}>
        <Row justify="space-around" align="middle" style={ { paddingTop: '25vw' } }>
          <Col>
            <Login />
          </Col>
        </Row>
      </div>
    </div>
  )
}
