import Head from 'next/head'
import Login from '../components/Login'
import { Row, Col } from 'antd'
import { useEffect } from 'react'
import { useStoreQuiz } from '../store/store'


export default function Home() {
  
  const quizStore = useStoreQuiz()

  useEffect(() => {
    const get = async () => {
        const res = await fetch(`${window.location.origin}/api/quizs`)
        const quizs = await res.json()
        quizStore.setQuizs(quizs)
    }
    get()
}, [quizStore])

  return (
    <div>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by Quiz App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'block' }}>
        <Row justify="space-around" align="middle" style={ { paddingTop: '25vw' } }>
          <Col>
            <Login />
          </Col>
        </Row>
      </div>
    </div>
  )
}
